export const ROUTES = {
  ROOT: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  APP: "/app",
  PROJECTS: "/projects",
  PROJECT_CREATE: "/projects/new",
  PROJECT_EDIT: "/projects/:projectId",
  ADMIN_ROOT: "/admin",
  ADMIN_USERS: "/admin/users",
  ADMIN_USER: "/admin/users/:userId",
  ADMIN_WORKSPACES: "/admin/workspaces",
  ADMIN_WORKSPACE: "/admin/workspaces/:workspaceId",
  PROFILE: "/profile",
  PROFILE_COMMON: "/profile/common",
  PROFILE_SESSIONS: "/profile/sessions",
  FINANCES: "/finances",
  LOGOUT: "/logout",
  WORKSPACE: "/workspace/:workspaceId",
  WORKSPACE_PROFILE: "/workspace/:workspaceId/profile",
  WORKSPACE_MEMBERS: "/workspace/:workspaceId/members",
  WORKSPACE_CREATE: "/workspaces/create",
};
